### ISSUE TITLE
bug using in *.bpl

### ISSUE THREAD

**Issue by Hodge2022** [Khojasteh/simple-graph#1]
![bug](https://user-images.githubusercontent.com/99470964/181701552-f8fd81d1-780c-4cdd-ab3d-f11d14cfd831.png)

When I use simplegraph in a bpl,the app crashed as the picture above showes.

**Comment by Hodge2022** [comment]
supplement：

**Comment by Hodge2022** [comment]
supplement:
my OS is windows 10 64bit,  and then IDE is delphi 10.3

**Comment by Khojasteh** [comment]
The problem you described is not a bug in SimpleGraph. 

It's mostly the configuration of your packages. It could also be because of the form in your package. Have you tried to load your form without SimpleGraph on it?

The BPL file of the package containing the SimpleGraph should be in your search path, not its source code.

**Comment by Hodge2022** [comment]
![image](https://user-images.githubusercontent.com/99470964/182004515-4893906d-00ef-4fc9-9df3-3020a30269ff.png)

**Comment by Hodge2022** [comment]
I Have Tyied to load a form without a Simplegraph on it, and everything is ok.

**Comment by Hodge2022** [comment]
[bplTest.zip](https://github.com/Khojasteh/simple-graph/files/9227803/bplTest.zip)

**Comment by Khojasteh** [comment]
Your code works fine on my Delphi installation.

**Comment by Hodge2022** [comment]
![image](https://user-images.githubusercontent.com/99470964/182051008-2d562698-e6c5-4483-ad78-153f5b46297c.png)
Could you send me the test files same as the picture shown above and the source?

**Comment by Hodge2022** [comment]
I have tyied on another machine , and I'm sorry that the result is same as before.

**Comment by Hodge2022** [comment]
I'm so sorry that I Changed the source file by adding unit name such as "Wina292pi.Windows, Winapi.Messages", and I created a new package named simplegraph292(not simplegraph), it works well now.
